package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRun(t *testing.T) {
	testCases := []struct {
		name         string
		args         []string
		setup        func(t *testing.T) (dir string, cleanup func())
		wantCode     int
		wantFile     string
		wantContains []string
	}{
		{
			name:     "missing spec flag",
			args:     []string{},
			wantCode: 1,
		},
		{
			name:     "invalid flag",
			args:     []string{"-invalid"},
			wantCode: 1,
		},
		{
			name:     "nonexistent spec",
			args:     []string{"-spec=nonexistent.yml"},
			wantCode: 1,
		},
		{
			name: "invalid yaml",
			setup: func(t *testing.T) (string, func()) {
				dir, err := os.MkdirTemp("", "oapixconstgen-test-*")
				if err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(filepath.Join(dir, "bad.yml"), []byte("not: valid: yaml:"), 0o600); err != nil {
					t.Fatal(err)
				}
				return dir, func() { os.RemoveAll(dir) }
			},
			wantCode: 1,
		},
		{
			name: "invalid package name",
			setup: func(t *testing.T) (string, func()) {
				dir, err := os.MkdirTemp("", "oapixconstgen-test-*")
				if err != nil {
					t.Fatal(err)
				}
				spec := `x-constants:
  int:
    foo: 1
`
				if err := os.WriteFile(filepath.Join(dir, "spec.yml"), []byte(spec), 0o600); err != nil {
					t.Fatal(err)
				}
				return dir, func() { os.RemoveAll(dir) }
			},
			wantCode: 1,
		},
		{
			name: "write error",
			setup: func(t *testing.T) (string, func()) {
				dir, err := os.MkdirTemp("", "oapixconstgen-test-*")
				if err != nil {
					t.Fatal(err)
				}
				return dir, func() { os.RemoveAll(dir) }
			},
			wantCode: 1,
		},
		{
			name: "all types from fixture",
			setup: func(t *testing.T) (string, func()) {
				dir, err := os.MkdirTemp("", "oapixconstgen-test-*")
				if err != nil {
					t.Fatal(err)
				}
				return dir, func() { os.RemoveAll(dir) }
			},
			wantCode: 0,
			wantContains: []string{
				"// Code generated by oapixconstgen. DO NOT EDIT.",
				"package testpkg",
				// int
				"DefaultPageSize", "int", "= 20",
				"MaxPageSize", "= 100",
				// int8
				"MinPriority", "int8", "= 1",
				"MaxPriority", "= 10",
				// int16
				"DefaultPort", "int16", "= 8080",
				// int32
				"MaxConnections", "int32", "= 10000",
				// int64
				"MaxFileSize", "int64", "= 5368709120",
				// uint
				"MinPasswordLength", "uint", "= 8",
				"MaxPasswordLength", "= 128",
				// uint8
				"MaxRetries", "uint8", "= 5",
				// uint16
				"BufferSize", "uint16", "= 4096",
				// uint32
				"CacheSize", "uint32", "= 1000000",
				// uint64
				"MaxMemory", "uint64", "= 17179869184",
				// float32
				"MinScore", "float32", "= 0",
				"MaxScore", "= 100",
				// float64
				"DefaultTimeout", "float64", "= 30.5",
				"Pi", "= 3.14159265359",
				// string
				"DefaultLocale", "string", `"en-US"`,
				// bool
				"DebugMode", "bool", "= false",
				"EnableCache", "= true",
			},
		},
		{
			name: "no constants",
			setup: func(t *testing.T) (string, func()) {
				dir, err := os.MkdirTemp("", "oapixconstgen-test-*")
				if err != nil {
					t.Fatal(err)
				}
				spec := `openapi: "3.0.0"
info:
  version: 1.0.0
  title: Empty
paths: {}
`
				if err := os.WriteFile(filepath.Join(dir, "empty.yml"), []byte(spec), 0o600); err != nil {
					t.Fatal(err)
				}
				return dir, func() { os.RemoveAll(dir) }
			},
			wantCode: 0,
		},
		{
			name: "unknown type ignored",
			setup: func(t *testing.T) (string, func()) {
				dir, err := os.MkdirTemp("", "oapixconstgen-test-*")
				if err != nil {
					t.Fatal(err)
				}
				spec := `x-constants:
  badtype:
    foo: 1
  int:
    bar: 2
`
				if err := os.WriteFile(filepath.Join(dir, "spec.yml"), []byte(spec), 0o600); err != nil {
					t.Fatal(err)
				}
				return dir, func() { os.RemoveAll(dir) }
			},
			wantCode: 0,
			wantContains: []string{
				"Bar int = 2",
			},
		},
		{
			name: "custom output file name",
			setup: func(t *testing.T) (string, func()) {
				dir, err := os.MkdirTemp("", "oapixconstgen-test-*")
				if err != nil {
					t.Fatal(err)
				}
				return dir, func() { os.RemoveAll(dir) }
			},
			wantCode: 0,
			wantFile: "myconsts.go",
			wantContains: []string{
				"// Code generated by oapixconstgen. DO NOT EDIT.",
				"package testpkg",
				"DefaultPageSize",
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			var buf bytes.Buffer
			args := tc.args

			var dir string
			if tc.setup != nil {
				var cleanup func()
				dir, cleanup = tc.setup(t)
				defer cleanup()

				switch tc.name {
				case "all types from fixture":
					args = []string{"-spec=.fixtures/api.yml", "-out=" + dir, "-pkg=testpkg"}
				case "no constants":
					args = []string{"-spec=" + filepath.Join(dir, "empty.yml"), "-out=" + dir}
				case "invalid yaml":
					args = []string{"-spec=" + filepath.Join(dir, "bad.yml"), "-out=" + dir}
				case "invalid package name":
					args = []string{"-spec=" + filepath.Join(dir, "spec.yml"), "-out=" + dir, "-pkg=123-invalid"}
				case "write error":
					args = []string{"-spec=.fixtures/api.yml", "-out=/nonexistent/dir"}
				case "unknown type ignored":
					args = []string{"-spec=" + filepath.Join(dir, "spec.yml"), "-out=" + dir, "-pkg=testpkg"}
				case "custom output file name":
					args = []string{"-spec=.fixtures/api.yml", "-out=" + dir, "-pkg=testpkg", "-file=" + tc.wantFile}
				}
			}

			code := run(args, &buf)
			if code != tc.wantCode {
				t.Errorf("got exit code %d, want %d\noutput: %s", code, tc.wantCode, buf.String())
			}

			if tc.wantContains != nil && dir != "" {
				outFileName := defaultOutFileName
				if tc.wantFile != "" {
					outFileName = tc.wantFile
				}
				content, err := os.ReadFile(filepath.Join(dir, outFileName))
				if err != nil {
					t.Fatalf("failed to read generated file: %v", err)
				}
				generated := string(content)
				for _, part := range tc.wantContains {
					if !strings.Contains(generated, part) {
						t.Errorf("missing expected part: %q\n\nGenerated:\n%s", part, generated)
					}
				}
			}
		})
	}
}

func TestCollectConstants(t *testing.T) {
	testCases := []struct {
		name      string
		spec      openAPISpec
		wantCount int
		wantTypes []string
	}{
		{
			name: "all types",
			spec: openAPISpec{
				XConstants: map[string]map[string]any{
					"int":     {"a": 1},
					"int8":    {"b": 2},
					"int16":   {"c": 3},
					"int32":   {"d": 4},
					"int64":   {"e": 5},
					"uint":    {"f": 6},
					"uint8":   {"g": 7},
					"uint16":  {"h": 8},
					"uint32":  {"i": 9},
					"uint64":  {"j": 10},
					"float32": {"k": 1.1},
					"float64": {"l": 2.2},
					"string":  {"m": "test"},
					"bool":    {"n": true},
				},
			},
			wantCount: 14,
			wantTypes: []string{"int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64", "string", "bool"},
		},
		{
			name:      "empty spec",
			spec:      openAPISpec{},
			wantCount: 0,
		},
		{
			name: "unknown type skipped",
			spec: openAPISpec{
				XConstants: map[string]map[string]any{
					"badtype": {"a": 1},
					"int":     {"b": 2},
				},
			},
			wantCount: 1,
			wantTypes: []string{"int"},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			constants := collectConstants(tc.spec)
			if len(constants) != tc.wantCount {
				t.Errorf("got %d constants, want %d", len(constants), tc.wantCount)
			}

			if tc.wantTypes != nil {
				gotTypes := make(map[string]bool)
				for _, c := range constants {
					gotTypes[c.goType] = true
				}
				for _, wantType := range tc.wantTypes {
					if !gotTypes[wantType] {
						t.Errorf("missing type %s", wantType)
					}
				}
			}
		})
	}
}

func TestGenerateCode(t *testing.T) {
	testCases := []struct {
		name      string
		pkg       string
		constants []typedConstant
		wantErr   bool
		wantParts []string
	}{
		{
			name: "int constant",
			pkg:  "api",
			constants: []typedConstant{
				{name: "maxLimit", goType: "int", value: 100, fmtVerb: "%d"},
			},
			wantParts: []string{"MaxLimit int = 100"},
		},
		{
			name: "float64 constant",
			pkg:  "api",
			constants: []typedConstant{
				{name: "ratio", goType: "float64", value: 0.75, fmtVerb: "%v"},
			},
			wantParts: []string{"Ratio float64 = 0.75"},
		},
		{
			name: "string constant",
			pkg:  "api",
			constants: []typedConstant{
				{name: "serviceName", goType: "string", value: "my-service", fmtVerb: "%q"},
			},
			wantParts: []string{`ServiceName string = "my-service"`},
		},
		{
			name: "bool constant",
			pkg:  "api",
			constants: []typedConstant{
				{name: "enableFeature", goType: "bool", value: true, fmtVerb: "%t"},
			},
			wantParts: []string{"EnableFeature bool = true"},
		},
		{
			name: "invalid package name",
			pkg:  "123-invalid-pkg",
			constants: []typedConstant{
				{name: "foo", goType: "string", value: "bar", fmtVerb: "%q"},
			},
			wantErr: true,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			code, err := generateCode(tc.pkg, tc.constants)

			if tc.wantErr {
				if err == nil {
					t.Error("expected error, got none")
				}
				return
			}

			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			generatedCode := string(code)
			for _, part := range tc.wantParts {
				if !strings.Contains(generatedCode, part) {
					t.Errorf("missing expected part: %q\n\nGenerated:\n%s", part, generatedCode)
				}
			}
		})
	}
}

func TestToExportedName(t *testing.T) {
	testCases := []struct {
		input string
		want  string
	}{
		{"defaultLimit", "DefaultLimit"},
		{"max_page_size", "MaxPageSize"},
		{"api_version", "ApiVersion"},
		{"simple", "Simple"},
		{"already_Capitalized", "AlreadyCapitalized"},
		{"", ""},
	}

	for _, tc := range testCases {
		t.Run(tc.input, func(t *testing.T) {
			got := toExportedName(tc.input)
			if got != tc.want {
				t.Errorf("toExportedName(%q) = %q, want %q", tc.input, got, tc.want)
			}
		})
	}
}
